# The following environment variables are required.
# They should be set in a CircleCI context called "docker".
#
# DOCKER_USER
# DOCKER_PASS
# DOCKER_REPO   eg. orgname/imagetag

version: 2

jobs:
  # test:
  #   docker:
  #     - image: alpine:latest

  #   working_directory: ~/project

  #   steps:
  #   - checkout
  #   - run: echo "Tests!"


  build_and_push:
    docker:
      - image: docker:latest

    working_directory: ~/project

    steps:
    - setup_remote_docker
    - checkout
    - run: echo "$DOCKER_PASS" | docker login -u $DOCKER_USER --password-stdin
    - run: |
        docker build -t ${DOCKER_REPO}:latest .

        if [[ "$CIRCLE_TAG" ]]; then
          docker tag ${DOCKER_REPO}:latest ${DOCKER_REPO}:${CIRCLE_TAG}
          docker push ${DOCKER_REPO}:${CIRCLE_TAG}
          docker push ${DOCKER_REPO}:latest
        else
          docker tag ${DOCKER_REPO}:latest ${DOCKER_REPO}:${CIRCLE_BRANCH}
          docker push ${DOCKER_REPO}:${CIRCLE_BRANCH}
        fi        

workflows:
  version: 2
  build_push:
    jobs:
      # - test:
      #     filters:
      #       tags:
      #         only: /.*/

      - build_and_push:
          context: docker
          # requires:
          #   - test          
          filters:
            tags:
              only: /^([0-9]+)\.([0-9]+)\.([0-9]+)/
